// Pure job logic ported from OpenCutAgent server/animation/jobs.js: manifest generation, the
// Scene.tsx scaffold, the brief.md and words.json builders, size and duration rules, the
// render.json sentinel reader, jobTitle. Plus the Borumi adapters: get_transcript responses
// (layers[].segments[].items triples in project ms) become the brief's narration lines, the
// words.json list and the context transcript.
//
// Nothing here touches the network or spawns anything; the CLI in scripts/job.mjs does the IO.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { round3, mmss, mmssMs, mmssMsPrecise } from "./fmt.mjs";

/** Jobs are always 30 fps compositions: the kit's SEC()/SCENE() hardcode 30 and Borumi conforms imports. */
export const FPS = 30;

export const RAW_MIN_SEC = 0.5, RAW_MAX_SEC = 600, RAW_DEFAULT_SEC = 5;
/** Segment jobs shorter than this are refused (upstream rule). */
export const MIN_JOB_SEC = 0.5;

export function newJobId(now = Date.now()) {
  return "anim-" + now.toString(36);
}

/**
 * A human title for a job, at most `max` characters: derived from the selected narration at
 * creation, replaced by the agent's own name for the animation once it builds one
 * (render.json "title"). Pure.
 */
export function jobTitle(text, max = 20) {
  const t = String(text == null ? "" : text).replace(/\s+/g, " ").trim();
  if (!t) return "Animation";
  if (t.length <= max) return t;
  const cut = t.slice(0, max - 1);
  const sp = cut.lastIndexOf(" ");
  return (sp > Math.floor(max / 2) ? cut.slice(0, sp) : cut).trimEnd() + "…";
}

/**
 * Validate a chosen output size. Returns {width,height} rounded DOWN to even numbers (h264
 * yuv420p refuses odd dimensions) or null when the values are not a usable size. Pure.
 */
export function normalizeSizeOverride(w, h) {
  const W = Math.round(Number(w)), H = Math.round(Number(h));
  if (!Number.isFinite(W) || !Number.isFinite(H)) return null;
  if (W < 16 || H < 16 || W > 8192 || H > 8192) return null;
  return { width: W - (W % 2), height: H - (H % 2) };
}

/** Raw-length validation in seconds, round3; null on garbage or out of range. Pure. */
export function normalizeRawDuration(sec) {
  const n = Number(sec);
  if (!Number.isFinite(n) || n < RAW_MIN_SEC || n > RAW_MAX_SEC) return null;
  return round3(n);
}

/**
 * Whole frames that fit inside [startMs, endMs]: floor, never round, so the render is never
 * longer than the range it replaces. Pure.
 */
export function durationInFramesFor(startMs, endMs, fps = FPS) {
  const ms = Number(endMs) - Number(startMs);
  if (!Number.isFinite(ms) || ms <= 0) return 0;
  return Math.floor((ms * fps) / 1000 + 1e-9);
}

/** The job's effective end: start + the rendered length, rounded down to whole ms. Pure. */
export function endMsEffectiveFor(startMs, durationInFrames, fps = FPS) {
  return Number(startMs) + Math.floor((durationInFrames * 1000) / fps);
}

/** Borumi's canvas preset from a size when the caller did not name one. Pure. */
export function inferCanvasFormat(width, height) {
  const w = Number(width), h = Number(height);
  if (!(w > 0) || !(h > 0)) return "custom";
  if (w === h) return "square";
  return w > h ? "landscape" : "vertical";
}

/* ============================ manifest ============================ */

const ident = (id) => "Scene_" + String(id).replace(/[^A-Za-z0-9_]/g, "_");

/** Source of the generated src/jobs/manifest.ts for these job entries. Pure. */
export function manifestSource(entries) {
  const lines = [
    "/**",
    " * AUTO-GENERATED by scripts/job.mjs. Do not edit by hand: the script",
    " * rewrites this file whenever a job is created or removed. Each job folder",
    " * (`src/jobs/<id>/`) owns its `Scene.tsx`; this file only registers them.",
    " */",
    'import type { JobEntry } from "./types";',
  ];
  for (const e of entries) lines.push(`import ${ident(e.id)} from "./${e.id}/Scene";`);
  lines.push("", "export const jobs: JobEntry[] = [");
  for (const e of entries) {
    lines.push(
      `  { id: ${JSON.stringify(e.id)}, component: ${ident(e.id)}, fps: ${e.fps}, width: ${e.width}, height: ${e.height}, durationInFrames: ${e.durationInFrames} },`
    );
  }
  lines.push("];", "");
  return lines.join("\n");
}

/** Rewrite the workspace manifest from the job folders actually on disk. Returns the entry count. */
export function regenerateManifest(dir) {
  const jobsDir = join(dir, "src", "jobs");
  const entries = [];
  let names = [];
  try { names = readdirSync(jobsDir, { withFileTypes: true }); } catch { names = []; }
  for (const e of names) {
    if (!e.isDirectory()) continue;
    const jp = join(jobsDir, e.name, "job.json");
    const sp = join(jobsDir, e.name, "Scene.tsx");
    if (!existsSync(jp) || !existsSync(sp)) continue;
    try {
      const j = JSON.parse(readFileSync(jp, "utf8"));
      if (j && j.id === e.name && j.fps > 0 && j.width > 0 && j.height > 0 && j.durationInFrames > 0) {
        entries.push({ id: j.id, fps: j.fps, width: j.width, height: j.height, durationInFrames: j.durationInFrames });
      }
    } catch { /* skip a corrupt job folder */ }
  }
  entries.sort((a, b) => a.id.localeCompare(b.id));
  writeFileSync(join(jobsDir, "manifest.ts"), manifestSource(entries));
  return entries.length;
}

/* ============================ scaffold ============================ */

/** The starter Scene.tsx the agent replaces. Pure. */
export function sceneScaffold(job, { styleHasSrc = false } = {}) {
  const transparent = job.background === "transparent";
  const styleHint = styleHasSrc
    ? `\n// This job's style ships its own components: import them from\n// "../../../styles/${job.style}/src" (the style guide documents each one).`
    : "";
  return `import React from "react";
import { useVideoConfig, interpolate, useCurrentFrame } from "remotion";
import { Canvas, SketchLayer } from "../../components";
import { SketchText } from "../../sketch";
import { tokens } from "../../theme/tokens";

// ${job.id}: scaffold scene. Read brief.md in this folder, then replace this
// placeholder with the real animation. Duration/size/fps are fixed (useVideoConfig).${styleHint}
const Scene: React.FC = () => {
  const { width, height, durationInFrames } = useVideoConfig();
  const frame = useCurrentFrame();
  const draw = interpolate(frame, [0, Math.min(45, durationInFrames)], [0, 1], {
    extrapolateRight: "clamp",
  });
  return (
    <Canvas transparent={${transparent}}>
      <SketchLayer>
        <SketchText
          x={width / 2}
          y={height / 2}
          size={tokens.fontSize.h3}
          color={tokens.color.inkMuted}
          opacity={draw}
        >
          ${JSON.stringify(job.id + " placeholder").slice(1, -1)}
        </SketchText>
      </SketchLayer>
    </Canvas>
  );
};

export default Scene;
`;
}

/* ============================ Borumi transcript adapters ============================ */

/**
 * Flatten a get_transcript response (words or blocks mode) into sorted items
 * `{start_ms, end_ms, text, layer_id, segment_id, scene_id, media_id}` in project ms.
 * Accepts one response object, an array of response chunks, an array of `[s, e, text]`
 * triples, or an array of already-flat items. Microphone layers win when present. Pure.
 */
export function extractItems(json) {
  const out = [];
  const pushResponse = (resp) => {
    const layers = Array.isArray(resp && resp.layers) ? resp.layers : [];
    const mics = layers.filter((l) => l && l.kind === "microphone");
    for (const layer of (mics.length ? mics : layers)) {
      for (const seg of (Array.isArray(layer.segments) ? layer.segments : [])) {
        for (const it of (Array.isArray(seg.items) ? seg.items : [])) {
          const item = itemFrom(it);
          if (!item) continue;
          item.layer_id = layer.id || null;
          item.segment_id = seg.segment_id || null;
          item.scene_id = seg.scene_id || null;
          item.media_id = seg.media_id || null;
          out.push(item);
        }
      }
    }
  };
  const itemFrom = (it) => {
    if (Array.isArray(it) && it.length >= 3) {
      const s = Number(it[0]), e = Number(it[1]);
      if (!Number.isFinite(s)) return null;
      return { start_ms: s, end_ms: Number.isFinite(e) ? e : s, text: String(it[2] == null ? "" : it[2]) };
    }
    if (it && typeof it === "object" && Number.isFinite(Number(it.start_ms))) {
      return { start_ms: Number(it.start_ms), end_ms: Number.isFinite(Number(it.end_ms)) ? Number(it.end_ms) : Number(it.start_ms), text: String(it.text == null ? "" : it.text) };
    }
    return null;
  };
  if (Array.isArray(json)) {
    for (const el of json) {
      if (el && typeof el === "object" && !Array.isArray(el) && Array.isArray(el.layers)) pushResponse(el);
      else { const item = itemFrom(el); if (item) out.push(item); }
    }
  } else if (json && typeof json === "object") {
    pushResponse(json);
  }
  out.sort((a, b) => a.start_ms - b.start_ms || a.end_ms - b.end_ms);
  return out;
}

/**
 * Words inside [startMs, endMs] as `{text, rel, end}` in seconds relative to the animation
 * start. A word may start up to `toleranceMs` before the in-point (clamped to 0); ends are
 * clamped to the range. Pure.
 */
export function wordsInRange(items, startMs, endMs, { toleranceMs = 50 } = {}) {
  const A = Number(startMs), B = Number(endMs);
  const relEnd = round3((B - A) / 1000);
  const out = [];
  for (const w of items || []) {
    const text = String(w.text == null ? "" : w.text).trim();
    if (!text) continue;
    if (!(w.start_ms >= A - toleranceMs && w.start_ms < B)) continue;
    const entry = { text, rel: round3(Math.max(0, w.start_ms - A) / 1000) };
    if (Number.isFinite(w.end_ms)) entry.end = round3(Math.min(relEnd, Math.max(0, w.end_ms - A) / 1000));
    out.push(entry);
  }
  return out;
}

/**
 * The narration lines for the brief: one per transcript block overlapping [A, B] (clipped to
 * the range), each with the words that fall inside it. Without blocks, one line per Borumi
 * words segment; with no words at all, a single "(no speech)" line. Returns
 * `{selected: [{index, relStart, relEnd, text}], wordsBySegment: Map}`. Pure.
 */
export function selectNarration({ words = [], blocks = [], startMs, endMs, toleranceMs = 50 }) {
  const A = Number(startMs), B = Number(endMs);
  const relEnd = round3((B - A) / 1000);
  const clip = (ms) => round3(Math.min(relEnd, Math.max(0, ms - A) / 1000));
  const inRange = wordsInRange(words, A, B, { toleranceMs });
  const rangeWords = (words || []).filter((w) => w.start_ms >= A - toleranceMs && w.start_ms < B);
  const selected = [];
  const wordsBySegment = new Map();

  const overlapping = (blocks || []).filter((b) => b.start_ms < B && b.end_ms > A && b.end_ms > b.start_ms);
  if (overlapping.length) {
    overlapping.forEach((b, i) => {
      selected.push({ index: i, relStart: clip(b.start_ms), relEnd: clip(b.end_ms), text: String(b.text || "").trim() });
    });
    // Each word joins the block whose span contains it, else the nearest block by start.
    rangeWords.forEach((w, k) => {
      let at = overlapping.findIndex((b) => w.start_ms >= b.start_ms && w.start_ms < b.end_ms);
      if (at < 0) {
        let best = Infinity;
        overlapping.forEach((b, i) => {
          const d = Math.min(Math.abs(w.start_ms - b.start_ms), Math.abs(w.start_ms - b.end_ms));
          if (d < best) { best = d; at = i; }
        });
      }
      const entry = inRange[k];
      if (!entry) return;
      if (!wordsBySegment.has(at)) wordsBySegment.set(at, []);
      wordsBySegment.get(at).push(entry);
    });
    return { selected, wordsBySegment };
  }

  if (rangeWords.length) {
    const groups = new Map();
    rangeWords.forEach((w, k) => {
      const key = w.segment_id || "range";
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key).push({ raw: w, entry: inRange[k] });
    });
    let i = 0;
    for (const list of groups.values()) {
      const first = list[0].raw, last = list[list.length - 1].raw;
      selected.push({
        index: i,
        relStart: clip(first.start_ms),
        relEnd: clip(Number.isFinite(last.end_ms) ? last.end_ms : last.start_ms),
        text: list.map((x) => x.entry.text).join(" "),
      });
      wordsBySegment.set(i, list.map((x) => x.entry));
      i++;
    }
    return { selected, wordsBySegment };
  }

  selected.push({ index: 0, relStart: 0, relEnd: relEnd, text: "" });
  return { selected, wordsBySegment };
}

/**
 * The context transcript for the brief: `>>> [m:ss] text` for blocks inside the range and
 * `- [m:ss] text` for the rest, limited to the target scene and its two neighbours when the
 * scene list is known, else to `maxLines` lines around the target. Pure.
 */
export function contextLines(blocks, startMs, endMs, { scenes = null, sceneId = null, maxLines = 400 } = {}) {
  const A = Number(startMs), B = Number(endMs);
  let list = (blocks || []).filter((b) => String(b.text || "").trim());
  if (Array.isArray(scenes) && scenes.length) {
    const sorted = [...scenes].sort((a, b) => Number(a.start_ms) - Number(b.start_ms));
    let at = sceneId ? sorted.findIndex((s) => s.id === sceneId) : -1;
    if (at < 0) at = sorted.findIndex((s) => A >= Number(s.start_ms) && A < Number(s.end_ms));
    if (at >= 0) {
      const keep = sorted.slice(Math.max(0, at - 2), at + 3);
      list = list.filter((b) => keep.some((s) => b.start_ms >= Number(s.start_ms) && b.start_ms < Number(s.end_ms)));
    }
  }
  const lines = list.map((b) => ({
    selected: b.start_ms < B && b.end_ms > A,
    text: `[${mmssMs(b.start_ms)}] ${String(b.text).trim()}`,
  }));
  let window = lines;
  if (lines.length > maxLines) {
    const firstSel = Math.max(0, lines.findIndex((l) => l.selected));
    const from = Math.max(0, Math.min(firstSel - Math.floor(maxLines / 2), lines.length - maxLines));
    window = lines.slice(from, from + maxLines);
  }
  return window.map((l) => `${l.selected ? ">>> " : "- "}${l.text}`);
}

/**
 * The narration's words for the job as `[{text, start, end}]` in seconds relative to the
 * animation start, sorted. Always written (an empty list for raw jobs) so
 * `import words from "./words.json"` resolves in every job. Pure.
 */
export function buildWordsJson(wordsBySegment = new Map()) {
  const out = [];
  for (const words of wordsBySegment.values()) {
    for (const w of words || []) {
      if (!w || typeof w.rel !== "number" || !String(w.text || "").trim()) continue;
      const entry = { text: String(w.text).trim(), start: w.rel };
      if (typeof w.end === "number" && w.end > w.rel) entry.end = w.end;
      out.push(entry);
    }
  }
  out.sort((a, b) => a.start - b.start);
  return out;
}

/* ============================ brief ============================ */

const esc = (s) => String(s == null ? "" : s);

/** The camera rectangle Samin's pinned-camera layout covers (canvas ratios), landscape only. */
export const CAMERA_KEEP_OUT = { x: 0.775, y: 0.715, w: 0.225, h: 0.285 };
export const CAMERA_KEEP_OUT_LINE = "The presenter's camera covers the bottom-right of the canvas (x >= 0.775, y >= 0.715). Keep essential content out of that rectangle.";

/** The "## Placement" section body: where the clip lands in Borumi and what that means for the design. Pure. */
export function placementLines(job) {
  const span = `project ${mmssMsPrecise(job.startMs)}-${mmssMsPrecise(job.endMsEffective != null ? job.endMsEffective : job.endMs)}`;
  const where = job.sceneName ? `${job.sceneName}, ${span}` : span;
  const lines = [];
  if (job.mode === "front") {
    lines.push(`In front of the footage (${where}): the render is a transparent overlay above the screen recording and the presenter's camera. Leave real transparency where the footage should show; strokes and text float over video, so keep them big and high-contrast.`);
  } else {
    lines.push(`Behind the camera (${where}): the render becomes the screen layer for this range and the presenter's camera is pinned on top of it.`);
    const fmt = job.canvasFormat || inferCanvasFormat(job.width, job.height);
    if (fmt === "landscape") lines.push(CAMERA_KEEP_OUT_LINE);
    else lines.push("The presenter's camera sits in a corner of the canvas (Borumi's corner layout). Keep essential content away from the bottom-right corner.");
  }
  return lines;
}

/**
 * Pull the planning markers out of a scene Script: `(ANIMATION: ...)` beats (multi-line until
 * the closing paren), `[IMAGE: ...]` lines with their prose and `Source:` lines, and
 * `[SHOW TABLE n]` marks with the table that follows. Returns [] when the script carries no
 * markers. Pure.
 */
export function extractScriptBeats(scriptText) {
  const text = String(scriptText || "");
  if (!text.trim()) return [];
  const out = [];
  const beatRe = /\(ANIMATION:\s*([\s\S]*?)\)(?=\s*(?:\n|$))/gi;
  let m;
  while ((m = beatRe.exec(text))) out.push(`- Animation beat: ${m[1].replace(/\s+/g, " ").trim()}`);
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (/^\[IMAGE:/i.test(line)) {
      const block = [line];
      for (let k = i + 1; k < lines.length && lines[k].trim() && !/^\[(IMAGE|SHOW TABLE|OPEN):/i.test(lines[k].trim()) && !/^\(ANIMATION:/i.test(lines[k].trim()); k++) block.push(lines[k].trim());
      out.push(`- ${block.join(" ")}`);
    } else if (/^\[SHOW TABLE\s*\d*\]/i.test(line)) {
      const block = [line];
      for (let k = i + 1; k < lines.length; k++) {
        const t = lines[k].trim();
        if (!t) { if (block.length > 1) break; continue; }
        if (!t.startsWith("|")) break;
        block.push(t);
      }
      out.push(`- ${block[0]}`);
      for (const row of block.slice(1)) out.push(`  ${row}`);
    } else if (/^Source:/i.test(line)) {
      out.push(`  ${line}`);
    }
  }
  return out;
}

/** The "## The user's plan for this beat" body, or [] when there is nothing to say. Pure. */
export function planLines({ userBrief = "", scriptText = "", scriptMaxLines = 60 } = {}) {
  const out = [];
  const brief = String(userBrief || "").trim();
  if (brief) out.push(`The user asked for: ${brief.replace(/\s+/g, " ")}`);
  const beats = extractScriptBeats(scriptText);
  if (beats.length) {
    if (out.length) out.push("");
    out.push("From the scene Script in Borumi:", ...beats);
  } else if (String(scriptText || "").trim()) {
    if (out.length) out.push("");
    out.push("The scene Script in Borumi (no explicit animation markers):");
    const lines = String(scriptText).trim().split("\n");
    out.push(...lines.slice(0, scriptMaxLines).map((l) => (l.trim() ? `> ${l}` : ">")));
    if (lines.length > scriptMaxLines) out.push(`> (${lines.length - scriptMaxLines} more lines not shown)`);
  }
  return out;
}

function headerLines(job) {
  const durSec = round3(job.durationInFrames / job.fps);
  return [
    `# Animation brief: ${job.id}`,
    "",
    `- Canvas: ${job.width}x${job.height} @ ${job.fps} fps`,
    `- Duration: ${job.durationInFrames} frames (${durSec}s). FIXED: fill exactly this time.`,
    `- Background: ${job.background === "transparent" ? "transparent (overlay on the footage; use <Canvas transparent>, or the style's own canvas component with `transparent`)" : "solid canvas (covers the footage like b-roll; use <Canvas>, or the style's own canvas component when the style guide names one)"}`,
    `- Style: ${job.style}`,
  ];
}

/**
 * The assignment document written into the job folder for the agent. Upstream's exact
 * section format (narration lines `[a.aas - b.bbs] text` with `words: w@t`, the context
 * transcript with `>>>` marks) plus the Borumi additions: "## Placement" always, and
 * "## The user's plan for this beat" when a user brief or a scene Script beat exists. Pure.
 */
export function buildBrief(job, { selected, transcriptLines, wordsBySegment = new Map(), placement = null, plan = [] }) {
  const lines = headerLines(job);
  if (job.seeFrames) {
    lines.push(
      "",
      "## Screen frames (frame-aware overlay)",
      "This animation draws ON the real footage under it: anchor your drawings to what is",
      "actually on screen (buttons, text, UI regions) and only while it is there. Start with",
      `src/jobs/${job.id}/frames-map.json and the contact sheets in public/frames/${job.id}/sheets/;`,
      "the frames guide (frames/SKILL.md) has the full workflow and rules."
    );
  }
  lines.push("", "## Placement", ...(placement || placementLines(job)));
  if (plan && plan.length) lines.push("", "## The user's plan for this beat", ...plan);
  lines.push(
    "",
    "## The narration you are animating (the selected timeline range)",
    "Times are seconds relative to the animation start (t=0 is your first frame).",
    "The narration plays on the Borumi timeline under your clip; sync your visual beats to it.",
    ""
  );
  for (const s of selected) {
    lines.push(`- [${s.relStart.toFixed(2)}s - ${s.relEnd.toFixed(2)}s] ${esc(s.text) || "(no speech)"}`);
    const words = wordsBySegment.get(s.index);
    if (words && words.length) {
      lines.push(`  words: ${words.map((w) => `${esc(w.text)}@${w.rel.toFixed(2)}`).join(" ")}`);
    }
  }
  lines.push(
    "",
    "## Full video transcript (context only)",
    "So you understand the topic around this moment. Lines marked >>> are the selected range.",
    ""
  );
  for (const t of transcriptLines) lines.push(t);
  lines.push("");
  return lines.join("\n");
}

/**
 * The brief for a RAW animation: no transcript, no narration, no selected range. Everything
 * the agent needs comes from the user's request. Pure.
 */
export function buildRawBrief(job, { placement = null, plan = [] } = {}) {
  const lines = headerLines(job);
  lines.push("", "## Placement", ...(placement || placementLines(job)));
  if (plan && plan.length) lines.push("", "## The user's plan for this beat", ...plan);
  lines.push(
    "",
    "## What you are animating",
    "This is a STANDALONE animation. It is NOT tied to the video's transcript:",
    "there is no narration to sync to and no script to follow. The user tells you",
    `in the chat exactly what to build. It lands on the timeline at ${mmss(job.range.startSec)},`,
    "so pace the whole thing to fill the fixed duration on its own.",
    ""
  );
  return lines.join("\n");
}

/* ============================ render.json ============================ */

/** The kit-side render.json sentinel the agent writes when the scene is ready. */
export function readRenderSignal(jobDir) {
  try {
    const parsed = JSON.parse(readFileSync(join(jobDir, "render.json"), "utf8"));
    const version = parseInt(parsed && parsed.version, 10);
    if (Number.isFinite(version) && version > 0) {
      return {
        version,
        notes: typeof parsed.notes === "string" ? parsed.notes : "",
        title: typeof parsed.title === "string" && parsed.title.trim() ? jobTitle(parsed.title) : null,
      };
    }
  } catch { /* absent or malformed: not ready */ }
  return null;
}

/** The slim job.json the kit-side folder carries (what regenerateManifest reads). Pure. */
export function kitJobJson(job) {
  return {
    id: job.id, fps: job.fps, width: job.width, height: job.height,
    durationInFrames: job.durationInFrames, background: job.background, style: job.style,
    audio: !!job.audio,
    outDir: job.outDir || null,
    projectPath: job.projectPath || null,
  };
}
